public enum EHelperAnim
{
    Idle = 1,
    Walk = 21,
    Run = 18,
    Equipped = 27,
    Jump = 10,
    WoodCutting = 5,
    WoodEpicCutting = 4,
    WoodLegendaryCutting = 4,
    Stun = 4,
    Harvest = 24,
    Sow = 30,
    Cultivate = 15,
    Water = 31,
    EatGround = 32,
    Happy = 2,
    EpicHarvest = 15,
    LegendaryHarvest = 3,
    NormalHarvest = 27,
    EpicSow = 15,
    LegendarySow = 44,
    LegendaryIce = 22,
}
